In [2]:
import numpy as np
import pandas as pd
import sklearn
import nltk

In [3]:
fake = pd.read_csv("Fake.csv")
true = pd.read_csv("True.csv")

## Creating lables i.e Target Vriable

In [4]:
fake["label"] = 0
true["label"] = 1

## Concatting fake and True datasets into one data

In [5]:
df = pd.concat([fake, true], ignore_index=True)

In [6]:
df.head(5)

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0


## Shuffling the data set

In [7]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [8]:
df.head(5)

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1


In [9]:
true[["title", "text"]].head(1)

,title,text
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...


In [10]:
print(true["text"][0])

WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a “fiscal conservative” on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way among Republicans, U.S. Representative Mark Meadows, speaking on CBS’ “Face the Nation,” drew a hard line on federal spending, which lawmakers are bracing to do battle over in January. When they return from the holidays on Wednesday, lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues, such as immigration policy, even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress. President Donald Trump and his Republicans want a big budget increase in military spending, while Democrats also want proportional increases for non-defense “discretionary” spending on programs that support educati

In [11]:
print(true["title"][0])

As U.S. budget fight looms, Republicans flip their fiscal script


In [12]:
print(fake["text"][0])

Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t eve

In [13]:
print(fake["title"][0])

 Donald Trump Sends Out Embarrassing New Year’s Eve Message; This is Disturbing


In [14]:
df.shape

(44898, 5)

In [15]:
df['label'].value_counts()

label
0    23481
1    21417
Name: count, dtype: int64

In [16]:
df.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(209)

In [18]:
df = df.drop_duplicates()

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.shape

(44689, 5)

In [21]:
df['combined_text'] = df['title'] + " " + df['text']

In [22]:
df['combined_text'].shape

(44689,)

In [23]:
df['combined_text'].isnull().sum()

np.int64(0)

In [24]:
df['combined_text'].duplicated().sum()

np.int64(5584)

In [25]:
df = df.drop_duplicates(subset=['combined_text'])

In [26]:
print(df.shape)

(39105, 6)


In [27]:
print(df['combined_text'].duplicated().sum())

0


In [28]:
df['combined_text'].shape

(39105,)

## Tokenization

In [29]:
# Import Libraries

import pandas as pd
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


# Download NLTK Resources
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')


# Stopwords, Lemmatizer

stop_words = set(stopwords.words('english'))

lemmatizer = WordNetLemmatizer()


# Text Preprocessing Function

def preprocess_text(text):

    # Lowercase
    text = text.lower()

    # Remove Special Characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Tokenization
    words = text.split()

    # Stopwords Removal
    words = [word for word in words
             if word not in stop_words]

    # Lemmatization
    words = [lemmatizer.lemmatize(word)
             for word in words]

    return " ".join(words)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [30]:
df['clean_text'] = df['combined_text'].apply(preprocess_text)

In [31]:
df['clean_text'].head(5)

0    ben stein call th circuit court committed coup...
1    trump drop steve bannon national security coun...
2    puerto rico expects u lift jones act shipping ...
3    oops trump accidentally confirmed leaked israe...
4    donald trump head scotland reopen golf resort ...
Name: clean_text, dtype: object

## Splitting into X(Features) and y(Target Variable)

In [32]:
X = df['clean_text']
y = df['label']

In [33]:
X

0        ben stein call th circuit court committed coup...
1        trump drop steve bannon national security coun...
2        puerto rico expects u lift jones act shipping ...
3        oops trump accidentally confirmed leaked israe...
4        donald trump head scotland reopen golf resort ...
                               ...                        
44890    burundi opposition platform boycott new round ...
44892    hillary message former miss universe called mi...
44894    pm may seek ease japan brexit fear trade visit...
44895    merkel difficult german coalition talk reach d...
44896    trump stole idea north korean propaganda parod...
Name: clean_text, Length: 39105, dtype: object

In [34]:
y

0        0
1        1
2        1
3        0
4        1
        ..
44890    1
44892    0
44894    1
44895    1
44896    0
Name: label, Length: 39105, dtype: int64

## Splitting into X_test,X_train,y_test,y_train(80-20)

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.8, random_state = 3)

In [36]:
X_train

39623    hillary brilliantly troll trump fledgling admi...
37990    hidden camera footage reveals disturbing fact ...
8665     kremlin say following situation ukraine luhans...
8405     risk brazil temer subside bungled jbs plea bar...
5227     u russian general talk facetoface syria washin...
                               ...                        
27552    trump slap travel restriction nkorea venezuela...
27770    mattis say complete accurate information niger...
11935    honduras opposition party ask disputed electio...
1698     college student express disgust trump first da...
6111     shocking video prove hillary willing endanger ...
Name: clean_text, Length: 31284, dtype: object

## Vectorization ft.BOW

In [37]:
from sklearn.feature_extraction.text import CountVectorizer

bow= CountVectorizer(max_features=5000,)

X_train_trans_b = bow.fit_transform(X_train)

In [38]:
X_train_trans_b

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4016993 stored elements and shape (31284, 5000)>

In [39]:
bow.get_feature_names_out

<bound method CountVectorizer.get_feature_names_out of CountVectorizer(max_features=5000)>

## Creating algo ft. X_train_trans_b 

In [40]:
from sklearn.neighbors import KNeighborsClassifier

bow_model = KNeighborsClassifier()

bow_model.fit(X_train_trans_b, y_train)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


## X_test_trans_b ft.bow

In [41]:
X_test_trans_b = bow.transform(X_test)

## X_test_trans to model for prediction

In [42]:
y_pred_b = bow_model.predict(X_test_trans_b)

In [43]:
y_pred_b

array([0, 1, 0, ..., 0, 0, 0], shape=(7821,))

## Evalution

In [44]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred_b)

In [45]:
score 

0.795678302007416

In [55]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred_b))

[[2840  666]
 [ 932 3383]]


## Vectorization ft.TF_IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X_train_trans_tfidf = tfidf.fit_transform(X_train)

In [41]:
X_train_trans_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4016993 stored elements and shape (31284, 5000)>

In [42]:
tfidf.get_feature_names_out

<bound method CountVectorizer.get_feature_names_out of TfidfVectorizer(max_features=5000)>

## Creating algo ft.X_train_trans_tfidf

In [43]:
from sklearn.neighbors import KNeighborsClassifier

model_tfidf = KNeighborsClassifier()

model_tfidf.fit(X_train_trans_tfidf, y_train)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


## X_test_trans_tfidf ft.tfidf

In [44]:
X_test_trans_tfidf = tfidf.transform(X_test)

## X_test_trans to model for prediction

In [45]:
y_pred_tfidf = model_tfidf.predict(X_test_trans_tfidf)

In [46]:
y_pred_tfidf

array([0, 1, 0, ..., 0, 0, 0], shape=(7821,))

## Evalution

In [47]:
from sklearn.metrics import accuracy_score
Score = accuracy_score(y_test, y_pred_tfidf)

In [48]:
Score

0.7048970719856796

## To Save Production File

In [50]:
import joblib

joblib.dump({'model': bow_model,'vectorizer': bow},'bow_model.pkl')

['bow_model.pkl']

In [51]:
bow_model_file = joblib.load('bow_model.pkl')

In [52]:
bow_model_file['model']

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [53]:
bow_model_file['vectorizer']


,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None
,stop_words,None
,token_pattern,'(?u)\\b\\w\\w+\\b'
,ngram_range,"(1, ...)"
,analyzer,'word'


In [54]:
joblib.dump({'vectorizer': tfidf,'model': model_tfidf},'tfidf_model.pkl')

NameError: name 'tfidf' is not defined

In [70]:
tfidf_model_files =joblib.load('tfidf_model.pkl')

In [71]:
tfidf_model_files['model']

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [72]:
tfidf_model_files['vectorizer']

,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None
,analyzer,'word'
,stop_words,None
,token_pattern,'(?u)\\b\\w\\w+\\b'
,ngram_range,"(1, ...)"
